# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

udo: false
language: python
python:
  - "2.7"
  - "3.4"
cache: apt
addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy nose
  - pip install pep8 python-coveralls
  - pip install .
script:
  - THEANO_FLAGS=floatX=float32 nosetests --with-coverage --cover-package=theanets --logging-level=INFO
after_success:
  - coveralls
# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: xinbian
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: xinbian/langevin_dynamics
    condition: $TOXENV == py27
