# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py
sudo: false
language: python
python:
  - "2.7"
  - "3.4"
addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy
  - pip install pytest-pep8 pytest-cov python-coveralls
  - python setup.py develop
script:
  - THEANO_FLAGS=floatX=float32 py.test -v --pep8 --cov=theanets --cov-report=term-missing
after_success:
  - coveralls
